spring.application.name=sports-booking-platform

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sports_booking_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mi_clave_super_secreta_para_sports_booking_2026_con_muchos_caracteres
jwt.expiration=86400000